site_name: Ma documentation DevSecOps
theme:
  name: material
nav:
  - Acceuil : index.md
  - Culture DevOps: 
    - 'Devops/Culture/introduction.md'
  # - Conteneurisation: 
  #   - 'Conteneurisation/information.md'
  #   - Docker: 
  #     - 'Conteneurisation/Docker/docker.md'
  #   - Kubernetes:
  #     - 'Conteneurisation/Kubernetes/kubernetes.md'
  # - Information: about.md
