site_name: Ma Documentation DevSecOps
theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.annotate
    - content.tabs.link
    - toc.integrate

nav:
  - Accueil: index.md
  - DevOps & DevSecOps:
    - Introduction: devops/devsecops.md
    - Culture DevOps:
      - Présentation: devops/culture/introduction.md
      - Piliers: devops/culture/piliers.md
      - Compréhension: devops/culture/comprehension.md
    - DevSecOps:
      - Introduction: devsecops/culture/introduction.md
      - En pratique: devsecops/culture/pratique.md
    - Pipeline sécurisé:
      - CI/CD: devsecops/cicd/pipelines.md
      - Outils: devsecops/cicd/outils.md
  - Cybersécurité:
    - Introduction: cybersecurity/introduction.md
    - Normes: cybersecurity/normes.md
    - Bonnes pratiques: cybersecurity/best-practices.md
  - Conteneurisation:
    - Docker:
      - Présentation: conteneurisation/docker/index.md
      - Bonnes pratiques: conteneurisation/docker/best-practices.md
      - Sécurité: conteneurisation/docker/security.md
    - Kubernetes:
      - Présentation: conteneurisation/kubernetes/introduction.md
      - Architecture: conteneurisation/kubernetes/architecture.md
      - Ressources: conteneurisation/kubernetes/resources.md
      - Sécurité: conteneurisation/kubernetes/security.md
  - API:
    - Introduction: api/index.md
    - Exercices pratiques: api/TP/exercice.md
  - Blog:
    - Articles: blog/index.md
    - Astuces: blog/Shortcut.md
    - Notes techniques: blog/tech-notes.md

plugins:
  - search
  - blog:
      blog_dir: blog
      blog_toc: true
  - glightbox  # Pour agrandir les images
  - git-revision-date-localized  # Pour afficher la date de dernière mise à jour

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.magiclink
