site_name: Ma documentation DevSecOps
theme:
  name: material
nav:
  - Acceuil : index.md
  - Culture DevOps: 
    - 'Devops/Culture/introduction.md'
  - Conteneurisation: 
    - Docker: 
      - 'Conteneurisation/Docker/index.md'
      - 'Conteneurisation/Docker/images.md'
  #     - 'Conteneurisation/Docker/docker.md'
  #   - Kubernetes:
  #     - 'Conteneurisation/Kubernetes/kubernetes.md'
  # - Information: about.md
  - Blog:
    - blog/index.md
plugins:
  - search
  - blog