site_name: Ma documentation DevSecOps
theme:
  name: material

nav:
  - Acceuil : index.md
  - Culture DevOps: 
    - 'Devops/Culture/introduction.md'
    - Pillier:
      - 'Devops/Culture/pillier_devops.md'
      - 'Devops/Culture/Comprehension.md'
    - Déploiement:
      - 'Devops/Deploiement/introduction.md'
  - DevSecOps: 
    - 'DevSecOps/Culture/introduction.md'
    - Dans la pratique:
      - 'DevSecOps/Culture/pratique.md'
  - Cybersécurité: 
    - 'Cybersecurity/introduction.md'
  - Conteneurisation: 
    - Docker: 
      - 'Conteneurisation/Docker/index.md'
      - 'Conteneurisation/Docker/images.md'
    - Kubernetes:
      - 'Conteneurisation/Kubernetes/Kubernetes.md'
      - 'Conteneurisation/Kubernetes/Kubernetes-architecture.md'
      - 'Conteneurisation/Kubernetes/Kubernetes-resources.md'
  - API:
    - 'api/index.md'
    - TP:
      - 'api/TP/exercice.md'
  - Blog:
    - blog/index.md
    - blog/Shortcut.md
plugins:
  - search
  - blog