site_name: Ma documentation DevSecOps
theme:
  name: material
  logo: assets/logo.png
nav:
  - Acceuil : index.md
  - Culture DevOps: 
    - 'Devops/culture.md'
  - Conteneurisation: 
    - 'Conteneurisation/information.md'
    - Docker: 
      - 'Conteneurisation/Docker/docker.md'
      
  - Information: about.md
