name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Déclenche le workflow lors de push sur la branche "main"
  pull_request:
    branches:
      - main  # Déclenche le workflow lors de pull request sur la branche "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Spécifiez la version de Python que vous utilisez

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material  # Installez MkDocs et le thème Material

    - name: Build MkDocs site
      run: |
        mkdocs build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./site  # Répertoire où MkDocs génère la documentation
